"""Report generation for issue changes."""

import os
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List


class ChangeReporter:
    """Generates reports for issue changes."""
    
    def __init__(self, reports_dir: str = "reports"):
        """Initialize reporter.
        
        Args:
            reports_dir: Directory to store report files
        """
        self.reports_dir = Path(reports_dir)
        self.reports_dir.mkdir(exist_ok=True)
    
    def generate_report(self, repo_changes: Dict[str, Dict[str, Any]]) -> str:
        """Generate a change report and save it to a file.
        
        Args:
            repo_changes: Dictionary mapping repo names to their changes
                         Format: {repo_name: {'new': [...], 'updated': [...], ...}}
            
        Returns:
            Path to the generated report file
        """
        timestamp = datetime.now().strftime('%Y-%m-%d-%H-%M-%S')
        report_file = self.reports_dir / f"changes-{timestamp}.md"
        
        # Generate report content
        report_lines = self._generate_report_content(repo_changes, timestamp)
        
        # Write to file
        with open(report_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(report_lines))
        
        return str(report_file)
    
    def _generate_report_content(self, repo_changes: Dict[str, Dict[str, Any]], 
                                 timestamp: str) -> List[str]:
        """Generate the content for a change report.
        
        Args:
            repo_changes: Dictionary mapping repo names to their changes
            timestamp: Timestamp string for the report
            
        Returns:
            List of report lines
        """
        lines = []
        lines.append("# GitHub Issues Change Report")
        lines.append("")
        lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")
        
        # Calculate totals
        total_new = sum(len(changes['new']) for changes in repo_changes.values())
        total_updated = sum(len(changes['updated']) for changes in repo_changes.values())
        total_unchanged = sum(len(changes['unchanged']) for changes in repo_changes.values())
        
        lines.append("## Summary")
        lines.append("")
        lines.append(f"- **New Issues:** {total_new}")
        lines.append(f"- **Updated Issues:** {total_updated}")
        lines.append(f"- **Unchanged Issues:** {total_unchanged}")
        lines.append(f"- **Repositories Checked:** {len(repo_changes)}")
        lines.append("")
        
        # Details per repository
        lines.append("## Changes by Repository")
        lines.append("")
        
        for repo_name, changes in sorted(repo_changes.items()):
            lines.append(f"### {repo_name}")
            lines.append("")
            
            # New issues
            if changes['new']:
                lines.append(f"#### New Issues ({len(changes['new'])})")
                lines.append("")
                for issue in changes['new']:
                    lines.append(f"- **#{issue['number']}**: {issue['title']}")
                    lines.append(f"  - State: {issue['state']}")
                    lines.append(f"  - Author: {issue['author']}")
                    lines.append(f"  - Created: {issue['created_at']}")
                    if issue['labels']:
                        labels_str = ', '.join(issue['labels'])
                        lines.append(f"  - Labels: {labels_str}")
                    lines.append(f"  - URL: {issue['url']}")
                    lines.append("")
            
            # Updated issues
            if changes['updated']:
                lines.append(f"#### Updated Issues ({len(changes['updated'])})")
                lines.append("")
                for update_info in changes['updated']:
                    issue = update_info['issue']
                    change_details = update_info['changes']
                    lines.append(f"- **#{issue['number']}**: {issue['title']}")
                    lines.append(f"  - URL: {issue['url']}")
                    lines.append(f"  - Changes:")
                    for change in change_details:
                        lines.append(f"    - {change}")
                    lines.append("")
            
            # Summary if no changes
            if not changes['new'] and not changes['updated']:
                lines.append("No changes detected.")
                lines.append("")
        
        lines.append("---")
        lines.append("")
        lines.append("*Report generated by GitHub Issue Extractor*")
        
        return lines
    
    def print_summary(self, repo_changes: Dict[str, Dict[str, Any]]):
        """Print a summary of changes to the console.
        
        Args:
            repo_changes: Dictionary mapping repo names to their changes
        """
        # Calculate totals
        total_new = sum(len(changes['new']) for changes in repo_changes.values())
        total_updated = sum(len(changes['updated']) for changes in repo_changes.values())
        total_unchanged = sum(len(changes['unchanged']) for changes in repo_changes.values())
        
        print("\n" + "=" * 60)
        print("CHANGE SUMMARY")
        print("=" * 60)
        print(f"New Issues:       {total_new}")
        print(f"Updated Issues:   {total_updated}")
        print(f"Unchanged Issues: {total_unchanged}")
        print(f"Repositories:     {len(repo_changes)}")
        print("=" * 60)
        
        # Details per repository
        for repo_name, changes in sorted(repo_changes.items()):
            print(f"\n{repo_name}:")
            print(f"  - New: {len(changes['new'])}")
            print(f"  - Updated: {len(changes['updated'])}")
            print(f"  - Unchanged: {len(changes['unchanged'])}")
            
            if changes['new']:
                print(f"\n  New Issues:")
                for issue in changes['new'][:5]:  # Show first 5
                    print(f"    - #{issue['number']}: {issue['title']}")
                if len(changes['new']) > 5:
                    print(f"    ... and {len(changes['new']) - 5} more")
            
            if changes['updated']:
                print(f"\n  Updated Issues:")
                for update_info in changes['updated'][:5]:  # Show first 5
                    issue = update_info['issue']
                    print(f"    - #{issue['number']}: {issue['title']}")
                if len(changes['updated']) > 5:
                    print(f"    ... and {len(changes['updated']) - 5} more")
        
        print("\n" + "=" * 60 + "\n")

